[[pages]]
path = "agent.py"
name = "Chatbot"
icon = "ğŸ¤–"

[[pages]]
path = "doc_manager/doc_manager_ui.py"
name = "Administracion"
icon = "âš™ï¸"

[[pages]]
path = "doc_querier.py"
name = "Consulta documentos"
icon = "ğŸ”"
