[[pages]]
path = "chat_ui.py"
name = "Chat Model"
icon = "ğŸ¤–"

[[pages]]
path = "agent.py"
name = "Agente"
icon = "ğŸ•µ"

[[pages]]
path = "documents_manager.py"
name = "Administracion"
icon = "ğŸ‘·â€â™‚ï¸"

[[pages]]
path = "services_check.py"
name = "Servicios"
icon = "ğŸ’»"