[[pages]]
path = "agent.py"
name = "Chatbot"
icon = "ğŸ¤–"

[[pages]]
path = "doc_manager/doc_manager_ui.py"
name = "Administracion"
icon = "ğŸ‘·â€â™‚ï¸"

[[pages]]
path = "services_check.py"
name = "Servicios"
icon = "ğŸ’»"