[[pages]]
path = "chatbot.py"
name = "Chatbot"
icon = "ğŸ¤–"

[[pages]]
path = "documents_manager.py"
name = "Administracion"
icon = "ğŸ‘·â€â™‚ï¸"

[[pages]]
path = "services_check.py"
name = "Servicios"
icon = "ğŸ’»"